
##################################### Authentication and Validation ##################################

############################## https://admin.chi.v6.pressero.com/docs/api/ ###########################

###
POST https://adminc.pro-matters.com/api/V2/Authentication
Content-Type: application/json

{
    "UserName": "rdickson@alphagraphics.com",
    "Password": "Ch33se1234",
    "SubscriberId": "7b4c94dc-b43e-4a2d-833a-58a6456148a2",
    "ConsumerID": "1807430a-9b0c-4a10-8ad8-341616d058fa"
}


###
GET https://admin.chi.v6.pressero.com/api/V2/Authentication/{6C070000-569F-0050-D112-08DD6659E6BF}/Validate


##################################### CRUD STATEMENTS#################################################

#******************* Orders - Get Order Details
    # https://admin.chi.v6.pressero.com/api/V2/Orders/{orderNumber}/Details
###
GET https://admin.chi.v6.pressero.com/api/V2/Orders/5317/Details HTTP/1.1
Authorization: token 6C070000-569F-0050-D112-08DD6659E6BF


#******************* Orders - Get Order Details (ID)
    # https://admin.chi.v6.pressero.com/api/V2/Orders/{orderID}/Details
###
GET https://admin.chi.v6.pressero.com/api/V2/Orders/04110000-569f-0050-7d0e-08dc00cc3736/Details HTTP/1.1
Authorization: token 6C070000-569F-0050-D112-08DD6659E6BF


#******************* Orders - Get Order Items
    # https://admin.chi.v6.pressero.com/api/V2/Orders/{OrderNumber}/Items

###
GET https://admin.chi.v6.pressero.com/api/V2/Orders/600/Items HTTP/1.1
Authorization: token 6C070000-569F-0050-D112-08DD6659E6BF


#******************* Orders - Get Order Payments
    # https://admin.chi.v6.pressero.com/api/V2/Orders/{orderNumber}/Payments

###
GET https://admin.chi.v6.pressero.com/api/V2/Orders/600/Payments HTTP/1.1
Authorization: token 6C070000-569F-0050-D112-08DD6659E6BF


#******************* Orders - Get Order Shipments
    # https://admin.chi.v6.pressero.com/api/V2/Orders/{orderNumber}/Shipments

###
GET https://admin.chi.v6.pressero.com/api/V2/Orders/600/Shipments HTTP/1.1
Authorization: token 6C070000-569F-0050-D112-08DD6659E6BF


#******************* Orders - Get Order CheckoutForm
    # https://admin.chi.v6.pressero.com/api/V2/Orders/{orderNumber}/CheckoutForm

###
GET https://admin.chi.v6.pressero.com/api/V2/Orders/600/CheckoutForm HTTP/1.1
Authorization: token 6C070000-569F-0050-D112-08DD6659E6BF


#******************* Users - Get The First 10 Users
    # https://admin.chi.v6.pressero.com/api/site/{domain}/users

###
GET https://admin.chi.v6.pressero.com/api/site/af.brandfulfillment.store/users/ HTTP/1.1
Authorization: token 6C070000-569F-0050-D112-08DD6659E6BF

#******************* 




#******************* 

###
DELETE https://admin.chi.v6.pressero.com/api/Calculators/741d0000-569f-0050-5bed-08dcd755c422 HTTP/1.1
Authorization: token AC040000-569F-0050-C1C7-08DCF37FA51D

#******************* 



###
GET https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/ HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E





### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/901b0000-569f-0050-e7b3-08dbbdf08e9c HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/901b0000-569f-0050-2e0d-08dbbdf0906d HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/901b0000-569f-0050-9947-08dbbdf09234 HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/901b0000-569f-0050-b445-08dbbdf0948e HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/60160000-569f-0050-f0ca-08dbbdf0965a HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/700a0000-569f-0050-c949-08dbbdf0ac7d HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/60160000-569f-0050-27cf-08dbbdf0aee1 HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/901b0000-569f-0050-53c0-08dbbdf0b386 HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/901b0000-569f-0050-1e5f-08dbbdf0b55c HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E
### 
DELETE https://admin.chi.v6.pressero.com/api/site/ahs.brandfulfillment.store/Assets/60160000-569f-0050-8d55-08dbbdf0b7af HTTP/1.1
Authorization: token F0080000-569F-0050-27AC-08DD05A6747E











###
GET https://ag679.corebridge.net/api/public/ExOrder
Authorization: basic 46ca4e64-af5f-47f5-9a23-d12b2f8c34f9
page: 2
pageSize: 10000


###















